### ISSUE TITLE
Current release throws "no such service: transpile"

### ISSUE THREAD

**Issue by chepo92** [paulhodel/jexcel#1484]
I'm trying to transpile release v4.6.0 with `docker-compose up transpile` , but I get: 
`no such service: transpile`

**Comment by hodeware** [comment]
That is deprected. If you wish to transpile, that process should be using your own project transpile such as npm build (for example in a react project).

**Comment by chepo92** [comment]
i'm not using any framework, just js and plugins, and I'm trying to add some functionalities to Jspreadsheets modifying current master branch

**Comment by hodeware** [comment]
If you wish to create new features, it is recommended to use events and custom editors. This is because when we release v5 if you have customize your version, you won't be able to take advantage of the new features, and you will need to implement all customizations again. But, if you implement your customizations on events, plugins, editors.... you can easily upgrade to newer versions since your customizations are decoupled... we have seem many, many developers leaving clients with custom versions... so every new upgrade it is a realy painful process... for that reason, we strongly discourage customizations in the core.

**Comment by hodeware** [comment]
If you are not using framework, and still want to create a bundle you can use webpack to do that.

**Comment by chepo92** [comment]
> If you wish to create new features, it is recommended to use events and custom editors. This is because when we release v5 if you have customize your version, you won't be able to take advantage of the new features, and you will need to implement all customizations again. But, if you implement your customizations on events, plugins, editors.... you can easily upgrade to newer versions since your customizations are decoupled... we have seem many, many developers leaving clients with custom versions... so every new upgrade it is a realy painful process... for that reason, we strongly discourage customizations in the core.

I want to contribute to this repo with some PR (maybe fix some issues and add some features) so i won't be out of sync, if you allow it, of course.

**Comment by hodeware** [comment]
Sure, all PR are welcomed. Of course we need to test the features to make sure won't break, and the main is make sure you test your features against all combinations of properties. Bear in mind, newer versions (from 4 to 5 for example) are not garantee to come from the master, since that is a complete refactor;

Again, use your judgment to see what would be better as a custom event, plugins, extensions, editors, etc...

**Comment by chepo92** [comment]
Thanks,

that v5 is being open source developed somewhere ?

**Comment by hodeware** [comment]
v5 is not available yet.

**Comment by chepo92** [comment]
@hodeware , I tried using webpack but no luck, I get`Uncaught ReferenceError: jspreadsheet is not defined` when I try it in the browser, 
I also tried react building jspreadsheet code from source but I get a lot of warnings and errors during build (eg. Line 12:37:    'define' is not defined  no-undef)

what tools or procedures do you follow to produce a bundle to /dist folder from current source ? A little help would be very apreciated

**Comment by hodeware** [comment]
For now, the build is deprected and the package was build manually. There is a refactor in progress to organize the files moving to webpack. So, the currently the src = dist, with the expection of formula which was brought to the dist manually to keep browser compatibility.

In a near future the build would be:
npm run build
